// PDF Muster Roll / Salary Sheet Generator using jsPDF
import jsPDF from "jspdf";
import { calculateWorkerFinancials } from "./calculations";

export const generateMonthlyMusterPdf = ({ workers = [], site, attendance = [], transactions = [], monthStr }) => {
  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4"
  });

  const siteName = site?.name || "All Sites";
  const dateObj = new Date();
  const printDate = dateObj.toLocaleDateString("en-IN", { day: "2-digit", month: "short", year: "numeric" });

  // Title Banner
  doc.setFillColor(16, 185, 129); // Emerald Green
  doc.rect(0, 0, 210, 22, "F");

  doc.setFont("helvetica", "bold");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(16);
  doc.text("HAJRI BOOK - MONTHLY MUSTER ROLL", 14, 11);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.text(`Site: ${siteName} | Month: ${monthStr || "Current"} | Generated: ${printDate}`, 14, 18);

  // Table Header
  let y = 32;
  doc.setFillColor(243, 244, 246);
  doc.rect(14, y, 182, 8, "F");

  doc.setTextColor(55, 65, 81);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);

  doc.text("Worker Name", 16, y + 5.5);
  doc.text("Trade", 60, y + 5.5);
  doc.text("Rate", 90, y + 5.5);
  doc.text("P / HD / A", 108, y + 5.5);
  doc.text("OT (h)", 132, y + 5.5);
  doc.text("Earned (Rs)", 150, y + 5.5);
  doc.text("Balance (Rs)", 175, y + 5.5);

  y += 10;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);

  let totalEarnedSite = 0;
  let totalBalanceSite = 0;

  workers.forEach((worker, index) => {
    if (y > 270) {
      doc.addPage();
      y = 20;
    }

    const fin = calculateWorkerFinancials(worker, attendance, transactions);
    totalEarnedSite += fin.totalEarned;
    totalBalanceSite += fin.balanceDue;

    // Alternate row styling
    if (index % 2 === 1) {
      doc.setFillColor(249, 250, 251);
      doc.rect(14, y - 4, 182, 7, "F");
    }

    doc.setTextColor(17, 24, 39);
    doc.text(worker.name.substring(0, 22), 16, y);
    doc.setTextColor(107, 114, 128);
    doc.text(worker.trade || "Worker", 60, y);
    doc.setTextColor(17, 24, 39);
    doc.text(`Rs ${worker.rate}`, 90, y);
    doc.text(`${fin.presentCount} / ${fin.halfDayCount} / ${fin.absentCount}`, 108, y);
    doc.text(`${fin.totalOtHours}h`, 132, y);
    doc.text(`Rs ${fin.totalEarned}`, 150, y);

    // Balance in bold
    doc.setFont("helvetica", "bold");
    doc.setTextColor(16, 185, 129);
    doc.text(`Rs ${fin.balanceDue}`, 175, y);
    doc.setFont("helvetica", "normal");

    y += 7.5;
  });

  // Summary row
  y += 4;
  doc.setDrawColor(209, 213, 219);
  doc.line(14, y, 196, y);
  y += 6;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  doc.setTextColor(17, 24, 39);
  doc.text("TOTAL SITE EXPENDITURE & DUES:", 16, y);
  doc.text(`Rs ${totalEarnedSite}`, 150, y);
  doc.setTextColor(16, 185, 129);
  doc.text(`Rs ${totalBalanceSite}`, 175, y);

  // Footer Note
  doc.setFontSize(7.5);
  doc.setFont("helvetica", "italic");
  doc.setTextColor(156, 163, 175);
  doc.text("Generated by Thekadar Hajri Book — Digital Muster Roll & Wage Record.", 14, 288);

  const safeFileName = `Hajri_Muster_Roll_${(monthStr || "Current").replace(/\s+/g, "_")}.pdf`;
  doc.save(safeFileName);
};
